apiVersion: a
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: 
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":,"":"","serviceName":":","ingressName":":","hostname":"","allNodes":true}]'
  generation: 2
  labels:
    cattle.io/creator: 
    workload.user.cattle.io/workloadselector: 
  name: 
  namespace: 
  selfLink: 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: 
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: 
    spec:
      containers:
      - image: ImageName
        ports:
        - containerPort: 3333
          name: api-port
          protocol: TCP
        imagePullPolicy: Always
        name: 
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: 
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: 
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: 
spec:
  ports:
  - name: backend-port
    port: 
    protocol: 
    targetPort: 
  selector:
    workload.user.cattle.io/workloadselector: 